name: React CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.Phawatcharakorn }}" | docker login -u "${{ secrets.DOCKER_PHAWATCHARAKORN }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_PHAWATCHARAKORN }}/react-ci-cd-demo .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_PHAWATCHARAKORN }}/react-ci-cd-demo